### REGISTER

POST http://localhost:3001/api/register
Content-Type: application/json

{
"name":"mar",
"userName":"laWizard",
"lastName":"cortina",
"password":"rojoCampeon"
}


### USER BY ID

GET http://localhost:3001/api/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlck5hbWUiOiJ2Y2FzdGFnbmFyaSIsImlhdCI6MTY0NjQxMDUwNywiZXhwIjoxNjQ2NDk2OTA3fQ.dXQvc8cm4nzBpvra-2MkggTM3h8az5K_28JRcL1rM_w

### ALL USERS

GET http://localhost:3001/api/users
Authorization: Bearer $2b$16$5ZaVmOFlxxexoipUaqHIMeoH47fxipaN08cMj67P20QTCpEIV.BlC


### USERS BY userName

GET http://localhost:3001/api/users?userName=laWizard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlck5hbWUiOiJsYVdpemFyZCIsImlhdCI6MTY0NjkxNTk5NCwiZXhwIjoxNjQ3MDAyMzk0fQ.Is-yoop8EDaLN6VHpqp3mJgGsfXKzpWKVIjQkRr7sLg


### CREATE FAVORITE

POST http://localhost:3001/api/favorites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlck5hbWUiOiJ2Y2FzdGFnbmFyaSIsImlhdCI6MTY0NjQxMDUwNywiZXhwIjoxNjQ2NDk2OTA3fQ.dXQvc8cm4nzBpvra-2MkggTM3h8az5K_28JRcL1rM_w

{
"name": "top gun",
"url_image":"no hay img",
"tmdbId":"550"
}

### LOGIN

POST http://localhost:3001/api/login
Content-Type: application/json

{       
    "userName":"laWizard",
    "password":"123456"
        }
### LOGIN


### auth

GET http://localhost:3001/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlck5hbWUiOiJ2Y2FzdGFnbmFyaSIsImlhdCI6MTY0NjA2MDI4NSwiZXhwIjoxNjQ2MTQ2Njg1fQ.VF6xaXDqxmYU2oczr_PUBMTAGidiYqaJGU-NozJ-nsg


### auth
GET http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlck5hbWUiOiJ2Y2FzdGFnbmFyaSIsImlhdCI6MTY0NjA2MDI4NSwiZXhwIjoxNjQ2MTQ2Njg1fQ.VF6xaXDqxmYU2oczr_PUBMTAGidiYqaJGU-NozJ-nsg

